### ISSUE TITLE
Bokeh: Trouble running doc2dash on sphinx generated documentation

### ISSUE THREAD

**Issue by stvn66** [Kapeli/Dash-User-Contributions#1022]
I compiled the documentation for [bokeh](https://github.com/bokeh/bokeh/tree/master/sphinx) and was able to view the results by running `python docserver.py`.  I then successfully ran `doc2dash -Ajf -n bokeh ./_build/html` (though there were many failed attempts because of a bad soft-link.

When I load the resulting output using Dash, the result is drastically different visually from the web version and several of the links do not work.  

I forked your repos and pushed the compressed docset into my fork.  I was surprised to find there was already a bokeh docset as it is not visible from the Dash Downloads.  Were there problems with this previous version?  Any ideas on what is going wrong with the docset?

**Comment by Kapeli** [comment]
User contributed docsets show up in Preferences > Downloads > User Contributed. Bokeh should show up there.

I have no idea what's going wrong with your docset. Please [send the docset to me](https://kapeli.com/contact) and I'll look into it.

I'm closing the issue here because this repo is for contributing docsets, not for helping with generating them.
