### ISSUE TITLE
How to find the docsets

### ISSUE THREAD

**Issue by DallasBuyer** [Kapeli/Dash-User-Contributions#1227]
I think I'm asking a stupid question. I can't find the docsets here. In the README, there is a sentence to say "As soon as your docset gets distributed to my CDN, it will get removed from the repo automatically". I want to ask how can i download the docsets files in the CDN,is there a URL?

**Comment by Kapeli** [comment]
You can download docsets from Dash, in Preferences > Downloads > User Contributed.

**Comment by DallasBuyer** [comment]
thank you, but I use the zeal not dash, I can not find  the "User Contributed". Then how can I get the docsets?

**Comment by Kapeli** [comment]
Please contact Zeal's developer for help regarding Zeal.

**Comment by DallasBuyer** [comment]
thanks for your patient explanation!

**Comment by eamigo86** [comment]
Hi @DallasBuyer,
Did you find any url from the CDN to download the docset ? I also use Zeal

**Comment by michaelmrose** [comment]
Would be great if you could provide a url for the additional docsets

**Comment by jeroldhaas** [comment]
There are users that are very eager to consume these docsets, however they are not using MacOS or iOS, and thus are forced to use Zeal as the consuming product.

Requesting that end-users harass an open-source project maintainer to add a feature is a bit unreasonable. Rather would be easier to simply provide a URL (even redirect) to the respective repository. Building high walls and barrier to entry will not enhance the core product or content.

**Comment by Kapeli** [comment]
My core product is Dash. I can't provide support for Zeal and missing features in Zeal. I don't even remember the time when I've last used Zeal, probably 3-4 years ago. I have no idea what features Zeal supports currently. At the time of responding to this issue in January, I had no idea if Zeal started supporting User Contributed docsets or not. Now that I've looked things up, I know that it hasn't. I can't look things up everytime someone asks.

I've provided Zeal with the information it needs to download docsets from this repo at https://github.com/zealdocs/zeal/issues/170#issuecomment-71310603.

From there on, it's up to Zeal to distribute that information to its users and/or implement the feature. I can't look up that issue comment and reference Zeal users to it everytime someone asks, because it takes time that I'd rather spend on Dash and Dash support. I just tell users to ask the Zeal maintainer who is very helpful and responsive.

Making user contributed docsets support XML feeds (https://kapeli.com/docsets#dashdocsetfeed) is not something that has been requested before. They don't support it currently, it's not as simple as giving you an URL.

It would have been nicer if you opened an issue and asked me to support that, instead of claiming I'm requesting end-users to harass @trollixx.

**Comment by jeroldhaas** [comment]
I concede, and apologize if my tone came off as abrasive.

I didn't want to open a duplicate issue, so commented on this one.

Thank you for the additional information -- it may be precisely what is needed for others seeking a similar resolution.

**Comment by jeroldhaas** [comment]
For any others running into this issue, http://zealusercontributions.herokuapp.com/ (e.g.: http://zealusercontributions.herokuapp.com/docsets/Emacs.xml ) is the current lazyman method.
