### ISSUE TITLE
ClojureScript docset misses namespace information

### ISSUE THREAD

**Issue by mharju** [Kapeli/Dash-User-Contributions#2714]
Thanks for the contributed CLJS docs, they have been in quite an extensive use for me for a long time. However, after updating to Dash 5, the information about the namespace of the matches has disappeared. This makes it hard to know which one is the correct selection.

![image](https://user-images.githubusercontent.com/130086/78246575-0a2f4880-74f2-11ea-9b2e-569d3f8fd263.png)

**Comment by mharju** [comment]
@shaunlebron if there is something I can help with to get this working, I'll be happy  to help!

**Comment by shaunlebron** [comment]
1. how did the UI display it before?
2. does the official clojure docset do it better?

**Comment by mharju** [comment]
> 1. how did the UI display it before?

It displayed the namespace in conjunction with the match.

> 2. does the official clojure docset do it better?

Yes, it works like expected. See the attached screenshot.

![image](https://user-images.githubusercontent.com/130086/78323523-c2a0cf00-757a-11ea-86ca-39659bf41665.png)


Thanks!

**Comment by shaunlebron** [comment]
@Kapeli how might I add “hierarchy” information to the symbol index?  Like in your official clojure docs:

<img width="317" alt="Screen Shot 2020-04-03 at 7 49 05 PM" src="https://user-images.githubusercontent.com/116838/78414956-6377a480-75e4-11ea-8701-d6e5e6c31f57.png">

The SQLite index only takes `name`, `type`, and `path`.  Is the path somehow used to construct the hierarchy?

**Comment by Kapeli** [comment]
That menu is built from the [table of contents](https://kapeli.com/docsets#tableofcontents). It's only for the current page, not the entire docset. It's also no longer available in Dash 5.

Dash docsets do not have any hierarchy.

**Comment by shaunlebron** [comment]
@Kapeli how would you suggest attaching a namespace to the search results then?  like the following:

![](https://user-images.githubusercontent.com/130086/78323523-c2a0cf00-757a-11ea-86ca-39659bf41665.png)

**Comment by Kapeli** [comment]
Within the `path` field in the SQLite index, add this anywhere: `<dash_entry_titleDescription=%@>`, where `%@` is the namespace you want, percent-encoded.

**Comment by shaunlebron** [comment]
I appended `<dash_entry_titleDescription=cljs.core>` to the end of the path field as suggested, and it seems to have corrupted the paths:
<img width="1087" alt="Screen Shot 2020-04-09 at 5 00 36 PM" src="https://user-images.githubusercontent.com/116838/78944509-aeca0100-7a83-11ea-8291-0ab5ca3298d8.png">
Likely not compatible with Dash 2.2.6, but it’s the latest one I can get on High Sierra, I think:
<table>
<tr>
<td valign=top>
<img width="420" alt="Screen Shot 2020-04-09 at 4 51 24 PM" src="https://user-images.githubusercontent.com/116838/78943976-855ca580-7a82-11ea-8137-06026d423508.png">
</td>
<td>
<img width="586" alt="Screen Shot 2020-04-09 at 4 52 51 PM" src="https://user-images.githubusercontent.com/116838/78944009-94435800-7a82-11ea-9a7a-fea01e9b50c1.png">
</td>
</table>

@Kapeli If you’re open to suggestions, `titleDescription` might be a good field to add to the index,  so path can remain backward compatible.

**Comment by Kapeli** [comment]
Adding this makes the docset not work in Dash 2, yes. Dash 3+ is ok with it, but only Dash 5 displays it in the interface.

You can use Dash 4 on High Sierra: https://kapeli.com/downloads/v4/Dash.zip.

**Comment by shaunlebron** [comment]
@Kapeli thanks

@mharju I’m not likely to add this if it breaks Dash 2.  But returning to the original problem, I’m not even seeing cljs namespaces in Dash 4 search results.  Can you clarify what disappeared in Dash 5?

<img width="780" alt="Screen Shot 2020-04-10 at 10 12 49 AM" src="https://user-images.githubusercontent.com/116838/79001357-f13b1e80-7b13-11ea-880b-b83b58479421.png">

**Comment by mharju** [comment]
@shaunlebron the UI screenshot of yours looks the way it was before. So maybe the difference is that Dash 5 does not show it the way it sums the two matching `get-env`:s for instance. 

So – to elaborate, maybe it did not display anything before, but only added the garbled versions in the search?

**Comment by shaunlebron** [comment]
okay thanks.  i’ll have to leave it as is since I can only publish one version to this repo.

**Comment by Kapeli** [comment]
By default, those hashes come from the file names of the doc pages (e.g. filename of `/api/cljs.spec.impl.gen/fmap-02bd1f8596236925b11b67bbb95c74eb.html`). If it used to work before, it might have been because the file names contained something different before.

The same info is shown in Dash 2, 3 or 4 when you press platform icon of a search result or the badges that sometimes appear next to search results.

If you just want to disable this, you can set `DashDocSetDeclaredInStyle` to `originalName` in Info.plist.

Unfortunately there's no easy way to work around it apart from the path hack. Very few users still use Dash 2 and generally breaking support for it is not an issue.

@shaunlebron Any reason why not to use Dash 4 on High Sierra? Dash 2 has some known bugs in High Sierra (notice the tab bar isn't shown in your screenshots). As a frequent docset maintainer you're entitled to a free Dash license, so please [contact me](https://kapeli.com/contact) if you'd like a free license to try out Dash 4.

**Comment by shaunlebron** [comment]
@Kapeli thanks.  And oops, I forgot I added those hashes, as a lazy way to get around macOS filesystem not being case-sensitive.

https://github.com/Kapeli/Dash-User-Contributions/pull/2732 should fix it.  It prefixes the filenames with a namespace (for @mharju), and removes the hashes (safely).

Btw, I was only Dash 2 because I didn’t know about newer versions.  I don’t mind upgrading (and thanks for license offer!).  Luckily, the new docset is still compatible with Dash 2 (and likely Zeal if anyone uses that).

**Comment by mharju** [comment]
Thank you so much for this!

**Comment by mharju** [comment]
Just received an update to my Dash and this version works perfectly. Thanks again!

**Comment by shaunlebron** [comment]
thanks for making the issue, keep me in the loop if stuff looks weird again
