### ISSUE TITLE
Request: Next.js

### ISSUE THREAD

**Issue by manishrc** [Kapeli/Dash-User-Contributions#3056]
**52.7K** Stars on GitHub (30% as popular as React itself and almost as popular as Angular)
**1,366** Contributors
**993,124** Weekly Downloads on NPM

https://github.com/vercel/next.js

https://nextjs.org/docs/getting-started

**Comment by judewang** [comment]
@Kapeli Thanks for the User-Contributions' docset, but the Next.js docset has not being updated for years. I tried using the new Docset Generator provided by the latest version of Dash, but there are some javascript issue to check. 

![CleanShot 2023-08-31 at 12 26 00@2x](https://github.com/Kapeli/Dash-User-Contributions/assets/1559819/9dcd5453-b6f0-46ce-b62a-10d3228825cb)

Since Next.js became the most famous framework of React, we use the Next.js documentation more often than React. It's could be good if we have Next.js docset built in. Thanks.
