### ISSUE TITLE
CPAN docset almost ready

### ISSUE THREAD

**Issue by skarfacegc** [Kapeli/Dash-User-Contributions#348]
So I have a functional CPAN docset (with all docs downloaded locally!)

tar'ed and gzip -9 gives me a 140M tarball (down from 1.2G)

If I understand correctly I need the following:

- Tarball of my CPAN.docset
- Icons 16x16 and 32x32 (I have these in the docset already)
- json file 

Do the icons and json file go into the docset tarball or do they stay outside?  What's the best way for me to get you the docset (since it blows out githubs 100MB limit).  I can put it on dropbox ...

**Comment by Kapeli** [comment]
The icons and json file should not be inside the tgz. Follow the sample structure here: https://github.com/Kapeli/Dash-User-Contributions/tree/master/Sample_Docset. Don't worry about `specific_versions` as I don't think you'll be using it for CPAN.

Dropbox is fine. When you submit the pull request, add a comment with the Dropbox link and I'll take it from there.

Please note that the final tarball that gets distributed might be a bit larger than 140M, because it'll get converted to an indexed tar format which adds a bit of extra space. It shouldn't exceed 200M though.

**Comment by skarfacegc** [comment]
Just to make sure I grok what should be in the submission (I'm probably reading too much into this)

- README.md
- CPAN.docset.tgz
   - Contains the actual docset (plist/resources/database/html/etc)
- docset.json
- icon.png
- icon@2x.png


Also, I think I'm going to do one more run on this thing to add the TOC info.  Is there a way to add a CSS file as well, or do I need to inline everything?

**Comment by Kapeli** [comment]
Yep, those files are all that's needed. Don't worry too much about missing something, I'll check and let you know.

> Also, I think I'm going to do one more run on this thing to add the TOC info. Is there a way to add a CSS file as well, or do I need to inline everything?

The docset is just like any folder that contains HTML files. You can add a CSS file and then include it in your HTML files as per usual. Inline CSS would increase the unarchived size, so I'd recommend against it.

**Comment by skarfacegc** [comment]
awesome.  thanks, I should have something for you in the next few days.  (script takes about 26 hours to run)

**Comment by skarfacegc** [comment]
Hopefully this is the last run before I get something to you.  Added styling and syntax highlighting.  
![screen shot 2015-02-27 at 12 13 15 am](https://cloud.githubusercontent.com/assets/1668735/6407791/acaa5b48-be15-11e4-9102-08567dc5797b.png)

**Comment by Kapeli** [comment]
Looks good :+1:
