### ISSUE TITLE
Formatting is broken in Poco docset

### ISSUE THREAD

**Issue by stolowski** [Kapeli/Dash-User-Contributions#3838]
Formatting is broken in Poco docset - see the screenshots (Logger term is an example of this)

<img width="1608" alt="Zrzut ekranu 2022-08-18 o 14 04 00" src="https://user-images.githubusercontent.com/168604/185390249-bf100931-b7ab-4280-845f-61ad4bdefefd.png">
<img width="736" alt="Zrzut ekranu 2022-08-18 o 14 04 33" src="https://user-images.githubusercontent.com/168604/185390356-c3617497-1e6e-4689-bffa-b874128dcd0a.png">

**Comment by Kapeli** [comment]
// cc @wxk6b1203

**Comment by wxk6b1203** [comment]
When I first committed version 1.9.4 of this docset I copied HTML from the original DOC page and deleted the sidebar. Another committer uploaded a new version 1.10.x while forgetting to do this job.

I cannot find the committer of 1.10.1 because of @Kapeli squashing commitments on Mar 19, 2022, at 01:09.

I can try to fix this problem maybe before the Chinese New Year (2023-01-23), while I am busy facing unemployment these few months.
