### ISSUE TITLE
Zig Improvements

### ISSUE THREAD

**Issue by puqeko** [Kapeli/Dash-User-Contributions#3921]
I'm interested in contributing some improvements to the Zig docset currently maintained by @kassane. How best to go about this?

Proposed changes:
- Table of Contents support for improved navigation.
- Add type entries "Builtin", "Keyword", and "Type" for @ builtins, language keywords, and primitive types.
- Improved search results where guides display the the name of their parent guide as a menu description.
- Text Search enabled by default.
- Online redirection support.
- Specified main page in `info.plist`.
- *Add documentation for the [Zig Standard Library](https://ziglang.org/documentation/master/std/).

*Currently, the Zig docset includes only the [Zig Language Reference](https://ziglang.org/documentation/0.9.1/). Zig's [autodoc](https://github.com/ziglang/zig/wiki/How-to-contribute-to-Autodoc) feature for generating the std lib docs is still experimental but I think there is enough there to be useful and informative when used with Dash.

Cheers

**Comment by kassane** [comment]
Hi @puqeko

Great that you have shown interest in contributing to the zig documentation in docset.

I have a simple script in python3 that uses beautifulsoup. But I would still need to adjust HTML to avoid redundancy.
Last year I tried it in autodoc but the interface didn't interact very well. It may have solved this problem, or it would need some adjustments.

I will review the script I have and post it here if you wish (it is quite generic).

Really, I would appreciate some help since I have run out of time.


html tweak tip
- https://github.com/Kapeli/Dash-User-Contributions/issues/3774#issuecomment-1176154004

**Comment by puqeko** [comment]
Great! Happy to help and happy to have a look at your script.

The issue I found with autodoc was that its implemented as a dynamic web app which means it takes far too long to load results in Dash. This also makes it a pain to generate an index without knowledge of ZIR. It doesn't look like there is an option to output static html yet. A work around I've toyed with is to programmatically load the app in Node and render out each screen. It's slow and a bit of a hack but seems to do the job.

Code can be found [here](https://github.com/puqeko/zig2dash).

**Comment by kassane** [comment]
> Great! Happy to help and happy to have a look at your script.

[Here](https://gist.github.com/kassane/bf8f4c91fea82d42911b6714f3f423d4) my simple script test.
Obviously it would still need adjustments. If memory serves me well in my first attempt at generating db it needed manual adjustments to the static documentation. Because it was broken at several points.

> The issue I found with autodoc was that its implemented as a dynamic web app which means it takes far too long to load results in Dash. This also makes it a pain to generate an index without knowledge of ZIR. It doesn't look like there is an option to output static html yet. A work around I've toyed with is to programmatically load the app in Node and render out each screen. It's slow and a bit of a hack but seems to do the job.

Anyway, it still looks promising.
Exact, autodoc will be the most complicated although it is under development.

**Comment by puqeko** [comment]
How about something like [this](https://gist.github.com/puqeko/2c78036035b6c67aa5104ba3ddaf673f)? I'd added Table of Contents support, more type entires, menu descriptions, and online redirection support to your script.

If you're short of time I'd be happy to make a PR for 0.9.1 and perhaps a dev release of 0.10.0?

Regards the std lib, are you worried about redundancy and reproducibility with respect to [my node script](https://github.com/puqeko/zig2dash)? If so, I could have a think about a more robust python solution

**Comment by kassane** [comment]
It would be interesting if you could present a new update with your solution (v0.10) or fix v0.9.1.

Really, I don't know anything in nodejs just abstract to run some solutions. If you can improve the python script appreciate it is even nicer for other possible maintainers (who have time or interest).

But if your solution solves the autodoc great it could be reviewed.

**Comment by kassane** [comment]
@puqeko, please close this issue. Well, it's solved!
