### ISSUE TITLE
Best way to create docset from asciidoc?

### ISSUE THREAD

**Issue by WoLpH** [Kapeli/Dash-User-Contributions#449]
The logstash documentation would be very useful to have within Dash, but I'm not entirely sure what's the easiest way to convert asciidoc files.

The asciidoc files are automatically generated towards this repo: https://github.com/elastic/logstash-docs

But I'm not sure what would be the best way to convert this to a readable format for Dash. Preferably I'd create a script to automatically update the docs regularly using Travis.

**Comment by Kapeli** [comment]
As far as I know, there's no easy way to index asciidoc-generated docs. I also think it's impossible to make a script that can index arbitrary asciidoc-generated docs because they don't have a common structure.

My best recommendation: write your own generation script just for logstash. Follow the steps at https://kapeli.com/docsets#dashDocset
