### ISSUE TITLE
Issue with file paths

### ISSUE THREAD

**Issue by samnabi** [Kapeli/Dash-User-Contributions#492]
Hi there,

I keep getting a "File not found" message when I try to browse a docset I created. I've checked my paths and I'm not sure where the issue is.

The sqlite3 database is `Kirby.docset/Contents/Resources/docSet.dsidx`

Sample document: `Kirby.docset/Contents/Resources/Documents/docs/cheatsheet/camera/make.html`

Sample SQL query: `INSERT OR IGNORE INTO searchIndex(name, type, path) VALUES ('$camera->make()', 'Method', 'docs/cheatsheet/camera/make.html');`

I can make a pull request if you would like to see the files.

**Comment by Kapeli** [comment]
That looks fine. Upload the docset somewhere so I can take a look what's going on.

**Comment by samnabi** [comment]
I've uploaded it here: https://github.com/samnabi/Dash-User-Contributions/tree/master/docsets/Kirby

**Comment by Kapeli** [comment]
I've attached a screenshot of what your docSet.dsidx contains when opened in a SQLite app.

Paths should be `docs/cheatsheet/camera/make.html` instead of `Documents/docs/cheatsheet/camera/make.html`.

![screen shot 2015-06-12 at 15 58 51](https://cloud.githubusercontent.com/assets/1445635/8130551/f271115e-111b-11e5-8eb6-53d7c7438903.png)

**Comment by samnabi** [comment]
Thank you :) I guess I should have taken a good night's sleep before opening an issue.
