### ISSUE TITLE
Updated RFCs docset

### ISSUE THREAD

**Issue by pointlessone** [Kapeli/Dash-User-Contributions#5149]
I made a newer version of RFCs docset but it's 159 MB (tgz). I can upload it elsewhere.

I also intend to update it once in a while. What is the procedure for that?

---

Tangentially related question: are there instruction on how to generate an optimized index? The docset is rather big and take quite a while to do that in Dash. I don't see why it has to be done on every target computer and can't be pre-generated. Given that this is mostly prose docset, maybe pre-generated full-text search index would be useful, too.

**Comment by Kapeli** [comment]
> I made a newer version of RFCs docset but it's 159 MB (tgz). I can upload it elsewhere.

Please submit a pull request with all the changes needed, and a link to the tgz inside Dropbox or anywhere else.

> I also intend to update it once in a while. What is the procedure for that?

Repeat the above as often as needed.

> Tangentially related question: are there instruction on how to generate an optimized index?

This is not currently possible. I've chosen to make Dash generate the index locally because I update the format every now and then and that requires reindexing. Indexing should take less than 2-3mins even for large docsets, are you seeing something else?
