### ISSUE TITLE
Add React 0.14 docset

### ISSUE THREAD

**Issue by princed** [Kapeli/Dash-User-Contributions#688]
[Original repo](https://github.com/chenglou/react-dash) says React docset is now officially maintained by Dash. 
But there are no signs of actual version :(

**Comment by Kapeli** [comment]
What do you mean there are no signs of actual version?

**Comment by princed** [comment]
I mean there is no React 0.14 docset. Could you please publish it?

**Comment by Kapeli** [comment]
React is available in Dash in Preferences > Downloads > All Docsets since v3.1.0. The latest version of the docset is 0.14.0. If you don't see it, it means you're not using Dash 3.1.

**Comment by princed** [comment]
Well, it looks very disappointing now. One of my most-used open source docset stopped updating, and I have to install paid upgrade (in fact, buy Dash again for the full price) to be able to use it again. 
What's more, I had to create issue to understand the situation.

**Comment by girvo** [comment]
I've got the same problem as you @princed -- I paid for Dash and love it as a tool, but having React's latest docset hidden away unless I pay full price for the new version is a bit of a shame (even if I can understand why). Dash 2 works brilliantly, and the features that 3 offers aren't features I need, so I've never needed to upgrade...

**Comment by Kapeli** [comment]
It was the @chenglou's [decision to remove](https://github.com/chenglou/react-dash/issues/9#issuecomment-119071085) the React docset from User Contributed, not mine. If anyone decides to start maintaining a React docset in User Contributed again, I'll happily accept it, as long as it's different from the "official" docset.

It costs $10 to upgrade from Dash 2 to Dash 3. For upgrade issues please contact me directly: https://kapeli.com/contact.

**Comment by chenglou** [comment]
Yep, I removed it because it's a subset of what's now officially maintained. Not sure what's hidden away? It's in the official section now.

**Comment by girvo** [comment]
Like I said (but didn't communicate particularly well), I completely understand why the decision was made. When I say "hidden away", what I mean is that as far as my Dash installation is concerned, the React docs are only yours @chenglou and there's not much of an indication that there in fact is an updated officially supported docset: you'd only know that if one owned Dash 3!

@Kapeli I truly did not know about the upgrade path, thank you for letting me know! I bought Dash the day I downloaded it because it's an excellent product, but I had not seen anything mentioning an upgrade for existing users within Dash 2. Again, that makes sense; you wouldn't want to (nor be able to, for App Store users?) push something out letting them know, but there is also nothing on the main website from what I can find -- with the exception of the blog post that I found that explains the process of upgrading :)

I hope I didn't come across as rude, I certainly wasn't trying to!

**Comment by chenglou** [comment]
![screenshot 2016-02-12 21 03 41](https://cloud.githubusercontent.com/assets/1909539/13024996/24852556-d1cc-11e5-8f13-eeae7cd5fef8.png)

I do own a purchased Dash 3 and I do see (and use) the official react docs maintained by Kapeli. It's weird that you don't see it though? It's in the All Docsets section now btw, since it's official.

**Comment by girvo** [comment]
Sorry @chenglou I'm confusing the issue :) I (up until about 15 minutes ago when @Kapeli was nice enough to send me through an upgrade code) only had Dash 2, as I hadn't seen a need to upgrade for my personal use-case for Dash. In Dash 2, React v0.13.1 is the latest version as it's the latest version that you released as a community docset, but I couldn't see why it was only at that version until I found this issue. I've upgraded to Dash 3 and now all is well

**Comment by Kapeli** [comment]
I just realised ... I forgot to remove the React docset from User Contributed.
